# [SI客戶]正式環境
deploy_production:
  extends: .deploy
  variables: {
    ENV_FILE: deployment/env/production.env,
    # 需搭配nginx 設定指定位置
    PROJECT_FOLDER: ""
  }
  only:
    # 指定的branch
    - production
  tags:
    # 指定的gitlab-runner tag
    - fet-shared-runner
  # 開啟後為手動更版
  # when: manual